---
- name: 分发配置文件
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0755
  with_items:
    - { src: "templates/kube-proxy-config.yaml.j2", dest: "/opt/kubernetes/cfg/kube-proxy-config.yaml" }
    - { src: "templates/kube-proxy.service.j2", dest: "/usr/lib/systemd/system/kube-proxy.service" }

- name: 创建数据目录
  file:
    path: "{{ K8S_DIR }}/kube-proxy"
    state: directory
