---
- name: 分发配置文件
  template: 
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0755
  with_items:
    - { src: "templates/kubelet-config.yaml.j2", dest: "/opt/kubernetes/cfg/kubelet-config.yaml" }
    - { src: "templates/kubelet.service.j2", dest: "/usr/lib/systemd/system/kubelet.service" }
    - { src: "templates/csr-crb.yaml.j2", dest: "/opt/kubernetes/cfg/csr-crb.yaml"}

- name: 创建数据目录
  file:
    path: "{{ K8S_DIR }}/kubelet"
    state: directory
