---
- name: 创建 token
  shell: |
    kubeadm token create  --description kubelet-bootstrap-token  --groups system:bootstrappers:{{ inventory_hostname }} --kubeconfig ~/.kube/config
  register: node
- set_fact: NODE_BOOTSTRAP_TOKEN="{{node.stdout}}"
- name: 设置集群参数
  shell: |
    kubectl config set-cluster kubernetes --certificate-authority=/opt/kubernetes/ssl/ca.pem --embed-certs=true --server={{ KUBE_APISERVER }} --kubeconfig=/opt/kubernetes/cfg/kubelet-bootstrap.kubeconfig

- name: 设置客户端认证参数
  shell: |
    kubectl config set-credentials kubelet-bootstrap --token={{ NODE_BOOTSTRAP_TOKEN }} --kubeconfig=/opt/kubernetes/cfg/kubelet-bootstrap.kubeconfig

- name: 设置上下文参数
  shell: |
    kubectl config set-context default --cluster=kubernetes --user=kubelet-bootstrap --kubeconfig=/opt/kubernetes/cfg/kubelet-bootstrap.kubeconfig

- name: 设置默认上下文
  shell: |
    kubectl config use-context default --kubeconfig=/opt/kubernetes/cfg/kubelet-bootstrap.kubeconfig

- name: Bootstrap Token Auth 和授予权限
  shell: |
    kubectl create clusterrolebinding kubelet-bootstrap --clusterrole=system:node-bootstrapper --group=system:bootstrappers
  when: inventory_hostname == "k8s-node01"
