---
- name: 下载kubernetes-server相关二进制文件
  get_url:
    url: https://dl.k8s.io/v1.17.9/kubernetes-server-linux-amd64.tar.gz
    dest: /root/kubernetes-ansible/roles/kubectl/files/
  when:
    - inventory_hostname == "k8s-master01"
    - download == "true"
- name: 解压kubernetes-server
  unarchive:
    src: files/kubernetes-server-linux-amd64.tar.gz
    dest: /usr/local/src/
- name: 拷贝相关kubeserver可执行文件到主节点上
  copy:
    src: /usr/local/src/kubernetes/server/bin/{{ item }}
    dest:  /opt/kubernetes/bin
    mode: 0755
  with_items:
    - kubectl
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
    - kubeadm
    - kubectl
  when: ( inventory_hostname == 'k8s-master01' or inventory_hostname == 'k8s-master02' or inventory_hostname == 'k8s-master03' )
- name: 拷贝相关kubelet+kube-proxy可执行文件到工作节点上
  copy:
    src: /usr/local/src/kubernetes/server/bin/{{ item }}
    dest:  /opt/kubernetes/bin
    mode: 0755
  with_items:
    - kubelet
    - kube-proxy  
    - kubectl
    - kubeadm
  when: 
    - inventory_hostname != 'k8s-master01' 
    - inventory_hostname != 'k8s-master02'
    - inventory_hostname != 'k8s-master03'


