---
- name: 设置集群参数
  shell: |
    kubectl config set-cluster kubernetes --certificate-authority=/opt/kubernetes/ssl/ca.pem  --embed-certs=true --server={{ KUBE_APISERVER }} --kubeconfig=/opt/kubernetes/cfg/kubectl.kubeconfig
- name: 设置客户端认证参数
  shell: |
    kubectl config set-credentials admin --client-certificate=/opt/kubernetes/ssl/admin.pem --client-key=/opt/kubernetes/ssl/admin-key.pem --embed-certs=true --kubeconfig=/opt/kubernetes/cfg/kubectl.kubeconfig

- name: 设置上下文参数
  shell: |
    kubectl config set-context kubernetes --cluster=kubernetes --user=admin --kubeconfig=/opt/kubernetes/cfg/kubectl.kubeconfig

- name: 设置默认上下文
  shell: |
    kubectl config use-context kubernetes --kubeconfig=/opt/kubernetes/cfg/kubectl.kubeconfig

