---    
- name: 解压etcd安装包
  unarchive:
    src: files/etcd-v3.2.30-linux-amd64.tar.gz
    dest: /usr/local/src/

- name: 分发 etcd 二进制文件
  copy: 
    src: /usr/local/src/etcd-v3.2.30-linux-amd64/{{ item }}
    dest: /opt/kubernetes/bin/{{ item }}
    mode: 0755
  with_items:
    - etcd
    - etcdctl
- name: 分发配置文件
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0755
  with_items:
    - { src: "templates/etcd.conf.j2", dest: "/opt/kubernetes/cfg/etcd.conf" }
    - { src: "templates/etcd.service.j2", dest: "/usr/lib/systemd/system/etcd.service" }

