---
- name: 设置集群参数 
  shell: |
    kubectl config set-cluster kubernetes --certificate-authority=/opt/kubernetes/ssl/ca.pem --embed-certs=true --server={{ KUBE_APISERVER }} --kubeconfig=/opt/kubernetes/cfg/kube-scheduler.kubeconfig

- name: 设置客户端认证参数
  shell: |
    kubectl config set-credentials system:kube-scheduler --client-certificate=/opt/kubernetes/ssl/kube-scheduler.pem --client-key=/opt/kubernetes/ssl/kube-scheduler-key.pem --embed-certs=true --kubeconfig=/opt/kubernetes/cfg/kube-scheduler.kubeconfig
- name: 设置上下文参数
  shell: |
    kubectl config set-context system:kube-scheduler  --cluster=kubernetes  --user=system:kube-scheduler --kubeconfig=/opt/kubernetes/cfg/kube-scheduler.kubeconfig

- name: 创建 kubeconfig 文件
  shell: |
    kubectl config use-context system:kube-scheduler --kubeconfig=/opt/kubernetes/cfg/kube-scheduler.kubeconfig



