---
- name: 分配配置文件
  template:
    src: templates/kube-controller-manager.service.j2
    dest: /usr/lib/systemd/system/kube-controller-manager.service
    mode: 0755
- name: 创建数据目录
  file:
    path: "{{ K8S_DIR }}/kube-controller-manager"
    state: directory
