---
- name: 设置集群参数
  shell: |
    kubectl config set-cluster kubernetes  --certificate-authority=/opt/kubernetes/ssl/ca.pem --embed-certs=true --server={{ KUBE_APISERVER }} --kubeconfig=/opt/kubernetes/cfg/kube-controller-manager.kubeconfig

- name: 设置客户端认证参数
  shell: |
    kubectl config set-credentials system:kube-controller-manager  --client-certificate=/opt/kubernetes/ssl/kube-controller-manager.pem --client-key=/opt/kubernetes/ssl/kube-controller-manager-key.pem --embed-certs=true --kubeconfig=/opt/kubernetes/cfg/kube-controller-manager.kubeconfig

- name: 设置上下文参数
  shell: |
    kubectl config set-context system:kube-controller-manager --cluster=kubernetes --user=system:kube-controller-manager  --kubeconfig=/opt/kubernetes/cfg/kube-controller-manager.kubeconfig

- name: 创建 kubeconfig 文件
  shell: |
    kubectl config use-context system:kube-controller-manager --kubeconfig=/opt/kubernetes/cfg/kube-controller-manager.kubeconfig

- name: 创建一个 ClusterRoleBinding
  shell: |
    kubectl create clusterrolebinding controller-manager:system:auth-delegator --user system:kube-controller-manager --clusterrole system:auth-delegator
  ignore_errors: yes
  when: inventory_hostname == 'k8s-master01'
